### ISSUE TITLE
Posting a status yields a Http/Serialize error

### ISSUE THREAD

**Issue by noiob** [Aaronepower/Mammut#2]
Attempting to post a simple status that looks like this:
```rust
StatusBuilder {
    status: "look carefully ahead",
    in_reply_to_id: None,
    media_ids: None,
    sensitive: None,
    spoiler_text: None,
    visibility: None
}
```
using
```rust
post = mastodon.new_status(status);
```
yields an
```rust
Err(Http(Serialize(Custom("unsupported value"))))
```

**Comment by Aaronepower** [comment]
thanks for your issue, I've pushed up a new version that should give you a proper error messages now.

**Comment by noiob** [comment]
I get the exact same Error on 0.5.0, but `mastodon.verify()`, which worked on 0.4.0 now throws this Error:
```rust
Http(Serialize(ErrorImpl { code: Message("unknown variant `id`, expected `Ok` or `Err`"), line: 1, column: 5 }))
```

**Comment by Aaronepower** [comment]
Okay, I've uploaded a new version that *should* work.

**Comment by Aaronepower** [comment]
Okay, the problem was I `Account.website` should have been `Option<String>`. That's now been addressed and new_status should work.

**Comment by noiob** [comment]
I hate to say this, but it still doesn't work.

**Comment by Aaronepower** [comment]
@noiob Okay, I can now verify that post status does work. Sorry should have reopened before.

**Comment by noiob** [comment]
I was able to use post status. However, verify() is broken with the same error message as before.

**Comment by Aaronepower** [comment]
@noiob verify now works.

**Comment by noiob** [comment]
Thanks for all your help!
