### ISSUE TITLE
Serde Error on APIError

### ISSUE THREAD

**Issue by BrainBlasted** [Aaronepower/Mammut#22]

**Comment by BrainBlasted** [comment]
Sorry for the blank issue, submitted my accident. Here are some details:
```text
Opening https://mastodon.social/                                                                                                                                                                              
Auth Code from browser: ******************************************************
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Serde(ErrorImpl { code: Message("missing field `error`"), line: 1, column: 1068 })', libcore/result.rs:916:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:68
             at libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:381
   3: std::panicking::default_hook
             at libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:522
   7: rust_begin_unwind
             at libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:23
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:782
  11: trumpet::app::App::register
             at src/app.rs:367
  12: trumpet::app::App::login_or_register
             at src/app.rs:269
  13: trumpet::app::App::run
             at src/app.rs:48
  14: trumpet::main
             at src/main.rs:24
  15: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  16: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:480
  17: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  18: std::rt::lang_start_internal
             at libstd/panicking.rs:459
             at libstd/panic.rs:365
             at libstd/rt.rs:58
  19: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  20: main
  21: __libc_start_main
  22: _start
```
I think this is in the APIError struct. Maybe change `String` to `Option<String>`?

**Comment by Aaronepower** [comment]
Thank you for this issue! Can you verify if this is still an error?

**Comment by Aaronepower** [comment]
@BrainBlasted There was a bug, that version has been yanked. upgrade to 0.10.1

**Comment by jhaye** [comment]
I have been working on Trumpet and upgraded it to 0.10.1. The issue is still there.

**Comment by BrainBlasted** [comment]
Hey, thanks for forking Trumpet! Every fork means a lot to me. If you've made any progress, please send a PR. And thank you for the information

**Comment by Aaronepower** [comment]
The fix is now available on master you can use that by specifying your mammut dependency as `mammut = { git = "https://github.com/Aaronepower/mammut" }

**Comment by jhaye** [comment]
This is what i get now:
```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Api(ApiError { error: None, error_description: None })', /checkout/src/libcore/result.rs:916:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
  10: trumpet::app::App::register
  11: trumpet::app::App::login_or_register
  12: trumpet::main
  13: std::rt::lang_start::{{closure}}
  14: std::panicking::try::do_call
             at /checkout/src/libstd/rt.rs:59
             at /checkout/src/libstd/panicking.rs:480
  15: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:101
  16: std::rt::lang_start_internal
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:365
             at /checkout/src/libstd/rt.rs:58
  17: main
  18: __libc_start_main
  19: _start```

**Comment by Aaronepower** [comment]
@jhaye That is mammut working as intended. I would suggest looking at what the server is sending back using something like Postman on that request.

**Comment by jhaye** [comment]
Alright, thanks!

**Comment by jhaye** [comment]
So I have further investigated the issue and it stems from `Mastodon::instance()`, which is weird since just before that it calls `Mastodon::verify_credentials()` and it succeeds.

**Comment by Aaronepower** [comment]
@jhaye Thanks to that piece of information I was able to find out that `Instance` was wrong due to unwritten documentation on Mastodon. I have fixed that now in the latest master.

**Comment by jhaye** [comment]
Cool! Thanks for the amazing work. Everything is working as expected now.
