### ISSUE TITLE
Result from get_home_timeline is not a Vec

### ISSUE THREAD

**Issue by jhaye** [Aaronepower/Mammut#26]
`Mastodon::get_home_timeline()` only returns one single `Status` rather than `Vec<Status>`.  This seems to be the result of this part of the API being auto-generated.

Here is get_home_timeline in the docs: https://docs.rs/mammut/0.10.0/mammut/struct.Mastodon.html#method.get_home_timeline

**Comment by jhaye** [comment]
I did some further digging and it seems like the `paged_routes!` macro is the issue. Other functions generated by it like `follow_requests()`, `mutes()`, etc. all only return a single entity, instead of a list.

**Comment by Aaronepower** [comment]
@jhaye This has now been fixed in `0.10.1`.

**Comment by jhaye** [comment]
Thanks, that was fast!
