### ISSUE TITLE
Questions Regarding Account Struct

### ISSUE THREAD

**Issue by BrainBlasted** [Aaronepower/Mammut#27]
So, I am going through and trying to fix Trumpet, and I was wondering about a few decisions made when you were updating trumpet. Mainly, the `Page` struct. With the page struct, everything is now wrapped in multiple layers of structure. For example, Trumpet gets a list of accounts, the user chooses an account, and then we check if the user is already following them, then follow the user if not, printing a message otherwise. When now getting accounts, you have to navigate through a Page struct of accounts, check the options and results, and then get another page of accounts to check through. Why not return a Vec and let your users handle pagination? Is this an API change?

**Comment by jhaye** [comment]
This is an API change on Mammut's end. Mastodon's API hasn't changed. I basically went through the code and just tried making as little changes as possible and still getting it to compile.
I haven't completely looked through the pagination changes in Mammut, but to me this change makes sense. You have to navigate through the data anyways and this Page struct makes it really simple with having a next and prev attribute. Sure you have to handle all the results, but you would have to do that either way.

**Comment by Aaronepower** [comment]
@BrainBlasted As @jhaye has said, before the inclusion of the `Page` struct there was no way to handle Mastodon's pagination, as pagination in Mastodon is handled with the `Link` header, and this is how I am letting my users handle pagination. `initial_items` is the `Vec` of items that would have previously been returned by those routes. If I instead got every entry that wouldn't be efficient as every call to something that could be paginated would require multiple HTTP calls.
