### ISSUE TITLE
Cannot Authenticate With Pleroma Instances

### ISSUE THREAD

**Issue by BrainBlasted** [Aaronepower/Mammut#32]
Pleroma seems to be expecting different JSON than what Mammut sends. Here's the error sent:

```
Instance URL: https://pleroma.site
Could not autheticate with the Mastodon instance.
Check that you entered the url of an existing instance.
Http(
    Error {
        kind: Json(
            Error("missing field `redirect_uri`", line: 1, column: 132)
        ),
        url: None
    }
)
Instance URL: https://
```

**Comment by Aaronepower** [comment]
@BrainBlasted Thank you for this issue. Can you please provide what route/method you are calling.

**Comment by BrainBlasted** [comment]
```rust
        let mut masto_instance_url = String::new();
        print!("Instance URL: https://");
        stdout().flush().unwrap();
        stdin().read_line(&mut masto_instance_url).unwrap();

        masto_instance_url = format!("https://{}/", masto_instance_url.trim().to_string());

        let mut regist = Registration::new(masto_instance_url.clone());

        // Checks if the registration process can continue with current
        // url. If not, restarts the regostration process.
        if let Err(e) = regist.register(masto_app) {
            println!("Could not autheticate with the Mastodon instance.");
            println!("Check that you entered the url of an existing instance.");
            println!("{:#?}", e);
            return self.register();
        }

        let auth_url = regist.authorise().unwrap();

        let mut auth_code = String::new();

        println!("Opening {}", masto_instance_url);
```

**Comment by Aaronepower** [comment]
@BrainBlasted I'm closing this as wontfix as there doesn't seem to be anything I can do on my end. That site must be either running a forked or outdated version of mastodon neither of which are supported by mammut.

**Comment by BrainBlasted** [comment]
@Aaronepower The site is running Pleroma, not Mastodon, which is another piece of software. Other libraries/applications work with both, and others have run into this issue. It is definitely something that can be fixed on this end.

**Comment by BrainBlasted** [comment]
Please reconsider. Pleroma is not a GNU Social application, but another ActivityPub software that federates with Mastodon. Both use the same API.

After review, it seems like Mammut is setting a field to the wrong name. Mastodon resolves that but Pleroma doesn't. What you likely need to do is change `redirect_uris` to `redirect_uri`

**Comment by BrainBlasted** [comment]
As I said, it uses the same API as  Mastodon. The source is not blocked behind login, the proper URL is https://git.pleroma.social/pleroma/pleroma.The documentation is at https://git.pleroma.social/pleroma/pleroma/wikis.

The error is a http error, and from my understanding that means that Pleroma is returning that response after Mammut sends JSON

**Comment by Aaronepower** [comment]
@BrainBlasted It says Http because the error is from `reqwest` deserialising the oauth json into the `OAuth` struct. `Http` is an `mammut::Error`.

**Comment by BrainBlasted** [comment]
@Aaronepower looking into this, the Pleroma JSON returns only `client_id`, `client_secret`, and `id`. Aren't those all that's needed for registration?

**Comment by BrainBlasted** [comment]
According to [Mastodon's Oauth Details](https://github.com/tootsuite/documentation/blob/master/Using-the-API/OAuth-details.md), you only need to store `client_id` & `client_secret`. This means the rest that Pleroma doesn't return should not be mandatory, and can be `Option<FieldType>`.

**Comment by BrainBlasted** [comment]
@Aaronepower please take a look at #33 when you can. It fixes authentication with Pleroma instances.
