### ISSUE TITLE
Add Attachment::Meta

### ISSUE THREAD

**Issue by wariuni** [Aaronepower/Mammut#6]
Several days ago the description of `"meta"` attribute was added to [the documentation by TootSuite](https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#attachment).
But in spite of the description, the API returns a JSON like this:
```json
  ...
  "meta": {
    "original": {
      "aspect": 0.75,
      "height": 700,
      "size": "525x700",
      "width": 525
    },
    "small": {
      "aspect": 0.75,
      "height": 400,
      "size": "300x400",
      "width": 300
    }
  },
  ...
```
I counld't immidiately figure out the entities because I'm not familer with Ruby.
https://github.com/tootsuite/mastodon/blob/master/app/models/media_attachment.rb

For now, deserialization of `Attachment` doesn't fail by lack of `Attachment.meta`.

**Comment by wariuni** [comment]
Neither [Ruby binding by TootSuite](https://github.com/tootsuite/mastodon-api/blob/master/lib/mastodon/media.rb) nor [Python binding](https://github.com/halcy/Mastodon.py/blob/master/mastodon/Mastodon.py) seems to read `"meta"`, so perhaps we better wait until the documentation fixed.

**Comment by Aaronepower** [comment]
This has been added in 0.9
